### ISSUE TITLE
Can i have some help again?

### ISSUE THREAD

**Issue by Marblesarecool** [ModisWorks/modis#46]
I got to setup Modis and it's working okay, but just a question:
How do i setup modules other than Pingpong?
And also, bethebot module doesn't seems to work.

**Comment by Amcio** [comment]
Modis has some modules preinstalled (try using `!help`). But to unlock the full potential you might need a few api keys. Though the most useful and the one most people need is the google_api_key that allows for searching youtube.

To get it: 

https://console.developers.google.com/apis/dashboard 
create a project
https://console.developers.google.com/apis/api/youtube.googleapis.com/overview
click enable
https://console.developers.google.com/apis/credentials
create credentials -> API Key
Make sure not to restrict it

Also you can join [modis public discord](https://discord.gg/z83UGvK) to get help.

**Comment by Infraxion** [comment]
In response to bethebot, that module has always given us trouble, I'll make sure to look at it before we release v0.4

@YtnomSnrub is just about to finish up this semester of uni and I'm about to switch my job to part-time so we will have time to wrap up 0.4 and push it out. Looking at perhaps a month or two out.
